### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by ChimpGamer** [BentoBoxWorld/TwerkingForTrees#11] opened 2020-02-26 20:55 UTC
#### Describe the bug

I noticed this error in the console: https://pastebin.com/d1YvqykH.

#### Steps to reproduce the behavior

I'm not sure when this happens because I just saw it in the console while there were like 25 players online.

##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.11.1
Database: JSON
Loaded Game Worlds:
skyblock_world (SkyBlock): Overworld, Nether, [end_color]End
Loaded Addons:
Biomes 1.6.0.1 (ENABLED)
BSkyBlock 1.11.0 (ENABLED)
Challenges 0.8.0 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
EpicHooks 1.0.0 (ENABLED)
ExtraMobs 1.11.0.2 (ENABLED)
IslandFly 1.7.0 (ENABLED)
Level 1.9.3 (ENABLED)
Likes 1.7.0 (ENABLED)
Limits 1.9.0 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
TwerkingForTrees 1.1.2 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment] 2020-02-27 15:17
This is a server bug. What build number of paper are you on?

**Comment by ChimpGamer** [comment] 2020-02-27 15:17
Paper 1.15.2 build 120

**Comment by tastybento** [comment] 2020-02-29 01:22
I don't see a way to fix this from my end. I suggest that unless it becomes chronic that we just leave it be.

**Comment by ChimpGamer** [comment] 2020-02-29 01:26
Well it keeps happening everyday. Today it happend 2 times.

**Comment by tastybento** [comment] 2020-02-29 01:34
Can you upload the logs so I can see from the most recent?

I can try and file a bug on the Spigot tracker.

**Comment by ChimpGamer** [comment] 2020-02-29 01:37
[2020-02-29-1.log](https://github.com/BentoBoxWorld/TwerkingForTrees/files/4269779/2020-02-29-1.log)

**Comment by tastybento** [comment] 2020-03-03 17:11
(This looks like a duplicate of https://github.com/BentoBoxWorld/Level/issues/111).

From looking through your log I see a lot of these errors. Do you have a plugin that you know of that is unloading chunks or worlds? Here's an error that occurs in the log as soon as the server is brought up. It looks like Faxtice issues the /back command, the server tries to obtain a chunk but it's been unloaded. I don't know why chunks would be unloaded.

```
[16:15:02] [Server thread/INFO]: Faxtice issued server command: /back
[16:15:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to Spartan vBuild 335
java.lang.IllegalStateException: Chunk not there when requested: Unloaded ticket level [-62, 184]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$getChunkAt$5(ChunkProviderServer.java:397) ~[patched_1.15.2.jar:git-Paper-121]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:393) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.IChunkProvider.getChunkAt(SourceFile:16) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:393) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:994) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.Location.getChunk(Location.java:123) ~[patched_1.15.2.jar:git-Paper-121]
	at me.vagdedes.spartan.f.i.<init>(SpartanLocation.java:204) ~[?:?]
	at me.vagdedes.spartan.e.b.a(EventsHandler2.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-121]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:765) ~[patched_1.15.2.jar:git-Paper-121]
	at nl.torchcraft.torchcore.extensions.essentials.objects.EssentialsUser.teleport(EssentialsUser.java:256) ~[?:?]
	at nl.torchcraft.torchcore.extensions.essentials.objects.EssentialsUser.teleportBack(EssentialsUser.java:212) ~[?:?]
	at nl.torchcraft.torchcore.extensions.essentials.commands.BackCommand.onExecute(BackCommand.java:32) ~[?:?]
	at nl.torchcraft.torchcore.torchcore.utils.TCCommand.execute(TCCommand.java:58) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1821) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1629) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-121]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-121]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[16:15:02] [Server thread/INFO]: *--------- Rule match (packet) for Faxtice ---------
[16:15:02] [Server thread/INFO]: MATCH: ^An internal error occurred while attempting to perform this command.*
[16:15:02] [Server thread/INFO]: CATCH: An internal error occurred while attempting to perform this command
[16:15:02] [Server thread/INFO]: FINAL: [TC] Er heeft zich een fout voortgedaan bij het uitvoeren van het commando. Neem contact op met een Admin.
```

**Comment by ChimpGamer** [comment] 2020-03-03 20:39
I'm not aware of any plugin doing chunk unloading.

**Comment by ChimpGamer** [comment] 2020-03-10 15:33
It just caused our server to crash. https://pastebin.com/JwmwXHv4

**Comment by tastybento** [comment] 2020-03-11 01:26
Please try the latest build. It now explicitly loads chunks before growing a tree.

**Closed as completed** 2020-03-25 02:10 UTC
Labels: bug, duplicate, wontfix
